//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOKService
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOK_BANNER
    {
        public int BANNER_ID { get; set; }
        public string BANNER_DESC { get; set; }
        public string BANNER_FILE { get; set; }
        public Nullable<int> BANNER_LANGUAGE { get; set; }
        public Nullable<int> BANNER_ORDER { get; set; }
        public Nullable<System.DateTime> BANNER_PUBLISHDATE { get; set; }
        public Nullable<int> BANNER_TYPE { get; set; }
        public Nullable<int> BANNER_WIDTH { get; set; }
        public Nullable<int> BANNER_HEIGHT { get; set; }
        public string BANNER_FIELD1 { get; set; }
        public string BANNER_FIELD2 { get; set; }
        public string BANNER_FIELD3 { get; set; }
        public string BANNER_FIELD4 { get; set; }
        public string BANNER_FIELD5 { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public string UPDATE_USER { get; set; }
        public string BANNER_NAME { get; set; }
    }
}
