//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOKService
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOK_CATEGORIES
    {
        public KOK_CATEGORIES()
        {
            this.KOK_NEWS_CAT = new HashSet<KOK_NEWS_CAT>();
        }
    
        public int CAT_ID { get; set; }
        public string CAT_CODE { get; set; }
        public string CAT_NAME { get; set; }
        public string CAT_DESC { get; set; }
        public string CAT_URL { get; set; }
        public string CAT_TARGET { get; set; }
        public Nullable<int> CAT_STATUS { get; set; }
        public Nullable<int> CAT_ACCESS { get; set; }
        public Nullable<int> CAT_POSITION { get; set; }
        public Nullable<int> CAT_SHOWFOOTER { get; set; }
        public Nullable<int> CAT_ORDER { get; set; }
        public Nullable<int> CAT_PARENT_ID { get; set; }
        public string CAT_PARENT_PATH { get; set; }
        public Nullable<int> CAT_RANK { get; set; }
        public Nullable<int> CAT_ROWITEM { get; set; }
        public Nullable<int> CAT_PAGEITEM { get; set; }
        public Nullable<int> CAT_SHOWITEM { get; set; }
        public Nullable<int> CAT_PERIOD { get; set; }
        public Nullable<int> CAT_PERIOD_ORDER { get; set; }
        public Nullable<int> CAT_TYPE { get; set; }
        public Nullable<int> CAT_LANGUAGE { get; set; }
        public Nullable<int> CAT_COUNT { get; set; }
        public string CAT_SEO_TITLE { get; set; }
        public string CAT_SEO_DESC { get; set; }
        public string CAT_SEO_KEYWORD { get; set; }
        public string CAT_SEO_URL { get; set; }
        public string CAT_IMAGE1 { get; set; }
        public string CAT_IMAGE2 { get; set; }
        public string CAT_HISTORY { get; set; }
        public string CAT_FIELD1 { get; set; }
        public string CAT_FIELD2 { get; set; }
        public string CAT_FIELD3 { get; set; }
        public string CAT_FIELD4 { get; set; }
        public string CAT_FIELD5 { get; set; }
        public string CAT_CODE_EN { get; set; }
        public string CAT_NAME_EN { get; set; }
        public string CAT_DESC_EN { get; set; }
        public string CAT_SEO_TITLE_EN { get; set; }
        public string CAT_SEO_DESC_EN { get; set; }
        public string CAT_SEO_KEYWORD_EN { get; set; }
        public string CAT_SEO_URL_EN { get; set; }
        public string CAT_IMAGE3 { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public string UPDATE_USER { get; set; }
    
        public virtual ICollection<KOK_NEWS_CAT> KOK_NEWS_CAT { get; set; }
    }
}
