//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOKService
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOK_NEWS_IMAGE
    {
        public int NEWS_IMG_ID { get; set; }
        public string NEWS_IMG_IMAGE1 { get; set; }
        public string NEWS_IMG_IMAGE2 { get; set; }
        public string NEWS_IMG_IMAGE3 { get; set; }
        public string NEWS_IMG_DESC { get; set; }
        public Nullable<int> NEWS_IMG_ORDER { get; set; }
        public Nullable<int> NEWS_IMG_SHOWTYPE { get; set; }
        public Nullable<int> NEWS_ID { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public string UPDATE_USER { get; set; }
    
        public virtual KOK_NEWS KOK_NEWS { get; set; }
    }
}
