//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOKService
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOK_NEWS_ATT
    {
        public int NEWS_ATT_ID { get; set; }
        public string NEWS_ATT_NAME { get; set; }
        public string NEWS_ATT_FILE { get; set; }
        public string NEWS_ATT_URL { get; set; }
        public Nullable<int> NEWS_ATT_ORDER { get; set; }
        public Nullable<int> EXT_ID { get; set; }
        public Nullable<int> NEWS_ID { get; set; }
        public string NEWS_ATT_FIELD1 { get; set; }
        public string NEWS_ATT_FIELD2 { get; set; }
        public string NEWS_ATT_FIELD3 { get; set; }
        public string NEWS_ATT_FIELD4 { get; set; }
        public string NEWS_ATT_FIELD5 { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public string UPDATE_USER { get; set; }
    
        public virtual KOK_NEWS KOK_NEWS { get; set; }
    }
}
