//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOKService
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOK_CONFIG
    {
        public int CONFIG_ID { get; set; }
        public string CONFIG_TITLE { get; set; }
        public string CONFIG_KEYWORD { get; set; }
        public string CONFIG_DESCRIPTION { get; set; }
        public Nullable<int> CONFIG_HITCOUNTER { get; set; }
        public string CONFIG_FAVICON { get; set; }
        public Nullable<int> CONFIG_ORDER { get; set; }
        public Nullable<int> CONFIG_LANGUAGE { get; set; }
        public string CONFIG_FIELD1 { get; set; }
        public string CONFIG_FIELD2 { get; set; }
        public string CONFIG_FIELD3 { get; set; }
        public string CONFIG_FIELD4 { get; set; }
        public string CONFIG_FIELD5 { get; set; }
        public string CONFIG_TITLE_EN { get; set; }
        public string CONFIG_KEYWORD_EN { get; set; }
        public string CONFIG_DESCRIPTION_EN { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public string UPDATE_USER { get; set; }
    }
}
